image: node:11.9.0

cache:
  paths:
   - node_modules/

before_script:
  - npm install

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: npm run test

build:
  stage: build
  script: npm run build

deploy:
  image: starefossen/ruby-node:latest
  stage: deploy
  environment:
    name: production
  only:
   - master
  script:
   - gem install sass
   - npm run deploy
  tags:
   - deploy
